title: Ethan Pippin
url: https://ethanpippin.com
baseurl: ""
githubURL: https://github.com/LePips
linkedinURL: https://www.linkedin.com/in/ethan-pippin-b0754a164/
leetcodeURL: https://leetcode.com/u/pippin2343/
google_analytics: G-WJ3WY1GP64
markdown: kramdown
